swagger: '2.0'
info:
  version: 'v2.0'
  title: Swagger API
host: any_cvm_ip:9440
basePath: /PrismGateway/services/rest/v2.0
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /file_groups/:
    get:
      description: List file groups.
      summary: listFileGroups
      operationId: FileGroupsGet
      produces:
      - application/json
      parameters:
      - name: uuid
        in: query
        required: false
        type: string
        description: UUID of file group
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Get.base.entitycollection&lt;get.dto.dr.filegroupdto&gt;'
          examples: {}
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /file_groups/{uuid}/delete_files:
    post:
      description: Remove files for a specific file group.
      summary: deleteFiles
      operationId: FileGroupsDeleteFilesByUuidPost
      produces:
      - application/json
      parameters:
      - name: uuid
        in: path
        required: true
        type: string
        description: UUID of file group
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Create.dto.primitivedto&lt;java.lang.boolean&gt;'
          examples: {}
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
definitions:
  Create.dto.primitivedto&lt;java.lang.boolean&gt;:
    title: create.dto.PrimitiveDTO&lt;java.lang.Boolean&gt;
    type: object
    properties:
      value:
        description: ''
        type: boolean
  Get.base.entitycollection&lt;get.dto.dr.filegroupdto&gt;:
    title: get.base.EntityCollection&lt;get.dto.dr.FileGroupDTO&gt;
    type: object
    properties:
      entities:
        description: ''
        type: array
        items:
          $ref: '#/definitions/Get.dto.dr.filegroupdto'
      error_info:
        $ref: '#/definitions/Get.base.errorinfo'
      metadata:
        $ref: '#/definitions/Get.base.metadata'
  Get.base.errorinfo:
    title: get.base.ErrorInfo
    type: object
    properties:
      count:
        description: ''
        type: integer
        format: int64
      entity_list:
        description: ''
        type: array
        items:
          type: string
      message:
        description: ''
        type: string
  Get.base.metadata:
    title: get.base.Metadata
    type: object
    properties:
      count:
        description: ''
        type: integer
        format: int32
      end_index:
        description: ''
        type: integer
        format: int32
      filter_criteria:
        description: ''
        type: string
      grand_total_entities:
        description: ''
        type: integer
        format: int32
      next_cursor:
        description: ''
        type: string
      page:
        description: ''
        type: integer
        format: int32
      previous_cursor:
        description: ''
        type: string
      search_string:
        description: ''
        type: string
      sort_criteria:
        description: ''
        type: string
      start_index:
        description: ''
        type: integer
        format: int32
      total_entities:
        description: ''
        type: integer
        format: int32
  Get.dto.errordetails:
    title: get.dto.ErrorDetails
    type: object
    properties:
      entity_id:
        description: ''
        type: string
      error_code:
        description: ''
        type: integer
        format: int32
      error_message:
        description: ''
        type: string
  State:
    title: state
    example: NOT_STARTED
    x-enum-elements:
    - name: NOT_STARTED
      description: ''
    - name: IN_PROGRESS
      description: ''
    - name: COMPLETED
      description: ''
    type: string
    enum:
    - NOT_STARTED
    - IN_PROGRESS
    - COMPLETED
  Get.dto.dr.filegroupdto:
    title: get.dto.dr.FileGroupDTO
    type: object
    properties:
      error_details:
        $ref: '#/definitions/Get.dto.errordetails'
      file_clone_paths:
        description: Cloned file in this file group.
        type: array
        items:
          type: string
      file_group_uuid:
        description: UUID of the file group.
        type: string
      protection_domain_name:
        description: Name of the protection domain the file group cloned from.
        type: string
      snapshot_id:
        description: Id of the snapshot the file group cloned from.
        type: string
      snapshot_uuid:
        description: UUID of the snapshot the file group cloned from.
        type: string
      state:
        $ref: '#/definitions/State'
      v_store_path_prefixes:
        description: Path prefixes of vStores in this file group.
        type: array
        items:
          type: string
      vm_ids:
        description: Ids of vms in this file group.
        type: array
        items:
          type: string
