swagger: '2.0'
info:
  version: 'v2.0'
  title: Swagger API
host: any_cvm_ip:9440
basePath: /api/nutanix/v2.0
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /iscsi_clients/:
    get:
      description: Retrieve Iscsi Client configuration
      summary: getIscsiClients
      operationId: IscsiClientsGet
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Get.base.entitycollection&lt;get.dto.acropolis.volumegroups.iscsiclientdto&gt;'
          examples: {}
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /iscsi_clients/{uuid}:
    get:
      description: Retrieve Iscsi Client configuration
      summary: getIscsiClient
      operationId: IscsiClientsByUuidGet
      produces:
      - application/json
      parameters:
      - name: uuid
        in: path
        required: true
        type: string
        description: Unique identifier for the iscsi client
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Get.dto.acropolis.volumegroups.iscsiclientdto'
          examples: {}
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    put:
      description: Modify an existing Iscsi Client configuration
      summary: updateVolumeGroup
      operationId: IscsiClientsByUuidPut
      produces:
      - application/json
      parameters:
      - name: uuid
        in: path
        required: true
        type: string
        description: UUID of the Iscsi client
      - name: body
        in: body
        required: true
        description: Update Iscsi client
        schema:
          $ref: '#/definitions/Update.dto.acropolis.volumegroups.iscsiclientdto'
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Update.dto.acropolis.volumegroups.iscsiclientdto'
          examples: {}
        default:
          description: Any internal exception while performing this operation
          schema: {}
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
definitions:
  Get.base.entitycollection&lt;get.dto.acropolis.volumegroups.iscsiclientdto&gt;:
    title: get.base.EntityCollection&lt;get.dto.acropolis.volumegroups.IscsiClientDTO&gt;
    type: object
    properties:
      entities:
        description: ''
        type: array
        items:
          $ref: '#/definitions/Get.dto.acropolis.volumegroups.iscsiclientdto'
      error_info:
        $ref: '#/definitions/Get.base.errorinfo'
      metadata:
        $ref: '#/definitions/Get.base.metadata'
  Get.base.errorinfo:
    title: get.base.ErrorInfo
    type: object
    properties:
      count:
        description: ''
        type: integer
        format: int64
      entity_list:
        description: ''
        type: array
        items:
          type: string
      message:
        description: ''
        type: string
  Get.base.metadata:
    title: get.base.Metadata
    type: object
    properties:
      count:
        description: ''
        type: integer
        format: int32
      end_index:
        description: ''
        type: integer
        format: int32
      filter_criteria:
        description: ''
        type: string
      grand_total_entities:
        description: ''
        type: integer
        format: int32
      next_cursor:
        description: ''
        type: string
      page:
        description: ''
        type: integer
        format: int32
      previous_cursor:
        description: ''
        type: string
      search_string:
        description: ''
        type: string
      sort_criteria:
        description: ''
        type: string
      start_index:
        description: ''
        type: integer
        format: int32
      total_entities:
        description: ''
        type: integer
        format: int32
  AuthType:
    title: auth_type
    example: CHAP
    x-enum-elements:
    - name: CHAP
      description: ''
    - name: NONE
      description: ''
    type: string
    enum:
    - CHAP
    - NONE
  Get.dto.acropolis.volumegroups.clientauthenticationdto:
    title: get.dto.acropolis.volumegroups.ClientAuthenticationDTO
    type: object
    properties:
      auth_type:
        $ref: '#/definitions/AuthType'
      password:
        description: Password of the supported authentication type
        type: string
  Get.dto.acropolis.volumegroups.iscsiclientdto:
    title: get.dto.acropolis.volumegroups.IscsiClientDTO
    type: object
    properties:
      client_address:
        description: Unique identifier for the client, it can be either iqn or ip address
        type: string
      enabled_authentications:
        description: List of supported authentication types
        type: array
        items:
          $ref: '#/definitions/Get.dto.acropolis.volumegroups.clientauthenticationdto'
      uuid:
        description: Uuid of the iscsi client
        type: string
  Update.dto.acropolis.volumegroups.clientauthenticationdto:
    title: update.dto.acropolis.volumegroups.ClientAuthenticationDTO
    type: object
    properties:
      auth_type:
        $ref: '#/definitions/AuthType'
      password:
        description: Password of the supported authentication type
        type: string
  Update.dto.acropolis.volumegroups.iscsiclientdto:
    title: update.dto.acropolis.volumegroups.IscsiClientDTO
    type: object
    properties:
      client_address:
        description: Unique identifier for the client, it can be either iqn or ip address
        type: string
      enabled_authentications:
        description: List of supported authentication types
        type: array
        items:
          $ref: '#/definitions/Update.dto.acropolis.volumegroups.clientauthenticationdto'
      uuid:
        description: Uuid of the iscsi client
        type: string
    required:
    - client_address
