swagger: '2.0'
info:
  title: Nutanix Legacy Procedural API
  #TODO description:
    #TODO - tune up this section (tables, validate this is correct, etc)
    #TODO - morph philosophy to more accurate reflect current state and declarative formatting
    #TODO - validate rule set is fully accurate (bounce off of super linter validation sets?)
  description: |
    # Introduction
    ## Overview
    * TODO: add v2 overview
      
    ## Terminology
    * TODO: add v2 terminology

    ## Rules  
    * TODO: add v2 rules

    ## Operatations (TODO?)
    * TODO: add v2 operations

  termsOfService: 'https://www.nutanix.com/support-terms'
    #TODO - validate with DS that we're aligned fully, and proper do-dads are where they need to be
  contact:
    name: Developer Support
    url: 'https://developer.nutanix.com'
  license:
    name: Nutanix End User License Agreement
    url: 'https://www.nutanix.com/eula'
    #TODO - validate with VH that we're aligned fully, and proper do-dads are where they need to be
  version: '2.0'
  #x-logo:
    #TODO - figure out logo / branding - this is likely a much larger thing, but wanted to annotate here anyways
    #url: Nutanix22.png
    #backgroundColor: '#FFFFFF'
basePath: /PrismGateway/services/rest/v2.0
schemes:
  - https
consumes:
  #TODO - validate MIME types in Prism Gateway
  - application/json
produces:
  - application/json
paths:
  # alerts
  /alerts:
    $ref: 'v2-2.0-yamls/alerts-src.yaml#/paths/base'
  /alerts/acknowledge:
    $ref: 'v2-2.0-yamls/alerts-src.yaml#/paths/acknowledge'

  # vms
  /vms:
    $ref: 'v2-2.0-yamls/vms-src.yaml#/paths/vms'
definitions:

parameters:
  #TODO - add more parameters for all uuid based validations
  uuid:
    in: path
    description: The UUID of the entity.
    format: UUID
    pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
    required: true
    type: string
    name: uuid
    #TODO - Can you $ref the pattern back to a signal definition?
responses:

securityDefinitions:
  basicAuth:
    type: basic
security:
  - basicAuth: []
tags:
  #TODO - productize this
  - name: alerts
    description: LOCK IT DOWN GOOSE!
  - name: app_blueprint
    description: why do we have this API exposed thru PE? 
  - name: authentication
    description: AuthN up on the corner
  - name: batch
    description: Batching so hard, might as well be a main frame
  - name: clusters
    description: honey bunches of data
  - name: containers
    description: containers, containers, containers, developers, developers, developers
  - name: data
    description: GIMME THE DATA, GOOSE!
  - name: directory_service
    description: ldap says what?
  - name: disks
    description: yahoo, a disk admin!
  - name: docker_registry
    description: counting down to this getting ripped out in 3, 2, 1
  - name: file_store
    description: like images, but not!
  - name: groups
    description: groups are like groups, but not at all like groups
  - name: hosts
    description: host mcHoster
  - name: idempotence_identifiers
    description: only programmers understand what this one does lol
  - name: images
    description: Like instagram, but for ISOs
  - name: ipmi_cmd
    description: yep, we built an API for IPMI
  - name: network_function_chain
    description: but, does it wobble to and fro?
  - name: network_security_rules
    description: GIMME THE FLOW, GOOSE!
  - name: oauth
    description: oauth2 say wut???
  - name: permission
    description: Always ask for forgiveness instead of permissions
  - name: portal_services
    description: connect to the portal, goose!
  - name: prism_central
    description: something about prism central internal APIs
  - name: project
    description: what about projects
  - name: remote_connections
    description: Like RDP, but for DR
  - name: role
    description: Aint pay no tolls, aint get no roles
  - name: secrets
    description: API exclusively reserved for tattle tales
  - name: ssh_user
    description: do you even SSH, bro?
  - name: subnet
    description: tomatoes tomates, subnets and potatoes
  - name: tasks
    description: task master makes the job go quickly
  - name: user_groups
    description: and the users fight in groups
  - name: users
    description: I FIGHT FOR THE USERS!
  - name: versions
    description: a version API? Who'd a thunk it?
  - name: vm_recovery_point
    description: recovery points? wow, novel!
  - name: vm_snapshot
    description: something about snaps
  - name: vms
    description: why should I care about VMs?
  - name: volume_group
    description: talk to me about VG's, goose?
  - name: webhook
    description: something about webhooks, possibly spiderman related
  - name: Pagination
    description: Document pagination policies here!!! This can take markdown
    x-traitTag: true
  - name: Sorting
    description: Document SORTING policies here!!! This can take markdown
    x-traitTag: true
  - name: Filtering
    description: Document FILTERING policies here!!! This can take markdown
    x-traitTag: true
externalDocs:
  #TODO - productize this
  description: Nutanix Online Product Documentation
  url: 'https://portal.nutanix.com'
x-tagGroups:
  #TODO - productize this
  - name: Operations
    tags: 
      - Pagination
      - Sorting
      - Filtering
  - name: virtual machines
    tags:
      - vms
      - subnet
      - alerts
  - name: images
    tags:
      - images
      - file_store
  - name: backup
    tags:
      - remote_connections
      - vm_recovery_point
      - vm_snapshot
  - name: flow
    tags:
      - network_function_chain
      - network_security_rules
  - name: infrastructure
    tags:
      - clusters
      - hosts
      - ipmi_cmd
      - secrets
      - webhook
  - name: storage
    tags:
      - volume_group
  - name: nutanix
    tags:
      - access_control_policies
      - authentication
      - directory_service
      - groups
      - idempotence_identifiers
      - permission
      - ssh_user
      - users
      - user_groups
      - tasks
      - versions
  - name: hidden
    tags:
      - app_blueprint #previously in calm section, this shouldnt be exposed on PE AFAIK
      - project #previously in calm section, this shouldnt be exposed on PE AFAIK
      - role #previously in calm section, this shouldnt be exposed on PE AFAIK 
      - batch
      - containers
      - data
      - disks
      - docker_registry
      - oauth
      - portal_services
      - prism_central